language: python

python:
  - 3.8

services:
  - docker

before_install:
  - pip install -U pip
  - pip install -U pytest

install:
  - cp ./bin/rumor-v0.2.3-linux-amd64 ./bin/rumor # move rumor into place for test discovery
  - pip install .

script: pytest -s
